database:
  host: localhost
  port: 3306
  user: root
  password: 123456
  db_name: scrapy_db
  db_charset: 'utf8'

logging:
  level: DEBUG

task:
  id: 1

request_info:
  platform: 'qiancheng'
  task_id: 1
  user_id: 19120418283
